//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by auv.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AUV_DIALOG                  102
#define IDC_AUV_DLG                     102
#define ID_TIMER_ELAPSED                104
#define ID_TIMER1                       111
#define IDR_MAINFRAME                   128
#define IDC_CURSOR1                     130
#define IDD_SETTINGS                    132
#define IDD_GENMF_DLG                   133
#define IDC_STATIC_DEPTH_SENSOR         1000
#define IDC_STATIC_ALTIMETER            1001
#define IDC_STATIC_ALTIm                1001
#define IDC_STATIC_ALTIm2               1002
#define IDC_STATIC_STATE                1005
#define IDC_LIST_CONTROL_PROGRAM        1006
#define IDC_STATIC_MISSION_PARTICULARS  1007
#define IDC_RADIO_AM                    1009
#define IDC_RADIO_RF                    1010
#define IDC_RADIO_BAT1_SAFE             1013
#define IDC_RADIO_BAT1_ALARMING         1015
#define IDC_RADIO_BAT1_CRITICAL         1016
#define IDC_RADIO_BAT2_SAFE             1017
#define IDC_RADIO_BAT2_ALARMING         1018
#define IDC_RADIO_BAT2_CRITICAL         1019
#define IDC_RADIO_BAT3_SAFE             1020
#define IDC_RADI_BAT3_ALARMING          1021
#define IDC_RADIO_BAT3_CRITICAL         1022
#define IDC_RADIO_BAT4_SAFE             1023
#define IDC_RADIO_BAT4_ALARMING         1024
#define IDC_RADIO_BAT4_CRITICAL         1025
#define IDC_RADIO_BAT5_SAFE             1026
#define IDC_RADIO_BAT5_ALARMING         1027
#define IDC_RADIO_BAT5_CRITICAL         1028
#define IDC_RADIO_BAT6_SAFE             1029
#define IDC_RADIO_BAT6_ALARMING         1030
#define IDC_RADIO_BAT6_CRITICAl         1031
#define IDC_RADIO_BAT7_SAFE             1032
#define IDC_RADIO_BAT7_ALARMING         1033
#define IDC_RADIO_BAT7_CRITICAL         1034
#define IDC_RADIO_BAT8_SAFE             1035
#define IDC_RADIO_BAT8_ALARMING         1036
#define IDC_RADIO_BAT8_CRITICAL         1037
#define IDC_RADIO_LEAK_PRESENT          1038
#define IDC_RADIO_LEAK_ABSENT           1039
#define IDC_LIST3                       1040
#define IDC_LIST_MFGEN                  1040
#define IDC_BUTTON_RECORD               1041
#define IDC_COMBO_COMMAND               1043
#define IDC_BUTTON_SUBMIT               1044
#define IDC_COMBO_MISSDUR               1045
#define IDC_LIST_BEARING                1046
#define IDC_COMBO_REFDEPTH              1046
#define IDC_EDIT1                       1060
#define IDC_EDIT_DEPTH                  1060
#define IDC_EDIT_HEAD                   1060
#define IDC_EDIT2                       1061
#define IDC_EDIT_ALTIMETER              1061
#define IDC_EDIT_SURGE                  1061
#define IDC_EDIT3                       1062
#define IDC_EDIT_CONDUCTIVITY           1062
#define IDC_EDIT_TIME                   1062
#define IDC_EDIT4                       1063
#define IDC_EDIT_SALINITY               1063
#define IDC_EDIT5                       1064
#define IDC_EDIT_TEMPERATURE            1064
#define IDC_EDIT6                       1065
#define IDC_EDIT_ROLL                   1065
#define IDC_EDIT7                       1066
#define IDC_EDIT_PITCH                  1066
#define IDC_EDIT8                       1067
#define IDC_EDIT_YAW                    1067
#define IDC_EDIT9                       1068
#define IDC_EDIT_RANGE                  1068
#define IDC_EDIT10                      1069
#define IDC_EDIT_BEARING                1069
#define IDC_COMM_AM                     1082
#define IDC_COMM_RF                     1083
#define IDC_LEAK_PRESENT                1084
#define IDC_LEAK_ABSENT                 1085
#define IDC_BAT1_SAFE                   1086
#define IDC_BAT1_ALARMING               1087
#define IDC_BAT1_CRITICAL               1088
#define IDC_BAT2_SAFE                   1089
#define IDC_BAT2_ALARMING               1090
#define IDC_BAT2_CRITICAL               1091
#define IDC_BAT3_SAFE                   1092
#define IDC_BAT3_ALARMING               1093
#define IDC_BAT3_CRITICAL               1094
#define IDC_BAT4_SAFE                   1095
#define IDC_BAT4_ALARMING               1096
#define IDC_BAT4_CRITICAL               1097
#define IDC_BAT5_SAFE                   1098
#define IDC_BAT5_ALARMING               1099
#define IDC_BAT5_CRITICAL               1100
#define IDC_BAT6_SAFE                   1101
#define IDC_BAT6_ALARMING               1102
#define IDC_BAT6_CRITICAL               1103
#define IDC_BAT7_SAFE                   1104
#define IDC_BAT7_ALARMING               1105
#define IDC_BAT7_CRITICAL               1106
#define IDC_BAT8_SAFE                   1107
#define IDC_BAT8_ALARMING               1108
#define IDC_BAT8_CRITICAL               1109
#define IDC_STATIC_LEAK                 1110
#define IDC_STATIC_COMM                 1111
#define IDC_LEAK_ABSENT2                1111
#define IDC_STATIC_BAT1                 1112
#define IDC_STATIC_BAT2                 1113
#define IDC_STATIC_BAT3                 1114
#define IDC_STATIC_BAT4                 1115
#define IDC_STATIC_BAT5                 1116
#define IDC_STATIC_BAT6                 1117
#define IDC_STATIC_BAT7                 1118
#define IDC_STATIC_BAT8                 1119
#define IDC_STATIC_SAFE                 1120
#define IDC_STATIC_ALARMING             1121
#define IDC_STATIC_CRITICAL             1122
#define IDC_STATIC_STATUS               1123
#define IDC_STATIC_SAFE2                1124
#define IDC_STATIC_ALARMING2            1125
#define IDC_RADIO3                      1126
#define IDC_STATIC_CRITICAL2            1126
#define IDC_RADIO4                      1127
#define IDC_STATIC_STATUS2              1127
#define IDC_RADIO5                      1128
#define IDC_RADIO6                      1129
#define IDC_CHECK_RF_CONNECTED          1134
#define IDC_CHECK_RF_DISCONNECTED       1135
#define IDC_CHECK_AM_CONNECTED          1136
#define IDC_EDIT_PROGSTATUS             1137
#define IDC_CHECK_AM_DISCONNECTED       1138
#define IDC_CHECK1                      1139
#define IDC_STATIC_PIC_ALTI             1140
#define IDC_EDIT11                      1141
#define IDC_EDIT12                      1142
#define IDC_STATIC_PIC_SURGE            1143
#define IDC_STATIC_PIC_DEPTH            1144
#define IDC_EDIT13                      1145
#define IDC_STATIC_PIC_HEADING          1145
#define IDC_STATIC_ORG                  1146
#define IDC_STATIC_ALTX                 1147
#define IDC_EDIT14                      1148
#define IDC_STATIC_ORG3                 1148
#define IDC_STATIC_ORG2                 1149
#define IDC_STATIC_ALTX2                1150
#define IDC_STATIC_ALTX3                1151
#define IDC_STATIC_ORG4                 1152
#define IDC_STATIC_ALTX4                1153
#define IDC_BUTTON2                     1154
#define IDC_BUTTON_LIGHT                1154
#define IDC_BUTTON_BAT1_SAFE            1155
#define IDC_BUTTON_BAT1_ALM             1156
#define IDC_BUTTON_BAT1_CRT             1157
#define IDC_BUTTON_BAT2_SAFE            1158
#define IDC_BUTTON_BAT2_ALM             1159
#define IDC_BUTTON_BAT2_CRT             1160
#define IDC_BUTTON_BAT3_SAFE            1161
#define IDC_BUTTON_BAT3_ALM             1162
#define IDC_BUTTON_BAT3_CRT             1163
#define IDC_BUTTON_BAT4_SAFE            1164
#define IDC_BUTTON_BAT4_ALM             1165
#define IDC_BUTTON_BAT4_CRT             1166
#define IDC_BUTTON_BAT5_SAFE            1167
#define IDC_BUTTON_BAT5_ALM             1168
#define IDC_BUTTON_BAT5_CRT             1169
#define IDC_BUTTON_BAT6_SAFE            1170
#define IDC_BUTTON_BAT6_ALM             1171
#define IDC_BUTTON_BAT6_CRT             1172
#define IDC_BUTTON_BAT7_SAFE            1173
#define IDC_BUTTON_BAT7_ALM             1174
#define IDC_BUTTON_BAT7_CRT             1175
#define IDC_BUTTON_BAT8_SAFE            1176
#define IDC_BUTTON_BAT8_ALM             1177
#define IDC_BUTTON_BAT8_CRT             1178
#define IDC_BUTTON_AM                   1179
#define IDC_BUTTON_RF                   1180
#define IDC_BUTTON_LEAK_PR              1181
#define IDC_BUTTON_LEAK                 1181
#define IDC_BUTTON_LEAK_PR2             1182
#define IDC_BUTTON_LEAK_AB              1182
#define IDC_STATIC_PIC_FLS              1185
#define IDC_EDIT15                      1187
#define IDC_BUTTON_OPENGL               1188
#define IDC_LIST1                       1190
#define IDC_LIST_STATUS                 1190
#define IDC_LIST_ACOUSTIC               1190
#define IDC_LIST2                       1191
#define IDC_LIST_GENMESS                1191
#define IDC_STATICA                     1192
#define IDC_LIST_ACOUSTICD              1192
#define IDC_STATIC_DEPTH                1193
#define IDC_STATIC_ALTI                 1194
#define IDC_STATIC_A_ALTI               1194
#define IDC_STATIC_RANGE                1195
#define IDC_STATIC_ALTI2                1195
#define IDC_STATIC_D_ALTI               1195
#define IDC_STATIC_BEARING              1196
#define IDC_STATIC_CONDUCTIVITY         1197
#define IDC_LIST4                       1197
#define IDC_LIST_DEVICE                 1197
#define IDC_STATIC_SALINITY             1198
#define IDC_BUTTON_SETTINGS             1198
#define IDC_STATIC_TEMPERATURE          1199
#define IDC_STATIC_DPTH_RNG             1199
#define IDC_STATIC_ROLL                 1200
#define IDC_STATIC_PITCH                1201
#define IDC_STATIC_YAW                  1202
#define IDC_STATIC_SURGE                1203
#define IDC_STATIC_ALTI_RNG             1204
#define IDC_STATIC_SURGE_RNG            1205
#define IDC_OPENGL_WINDOW               1206
#define IDC_BUTTON1                     1207
#define IDC_BUTTON_AUTO                 1207
#define IDC_STATIC_ELAPSED              1208
#define IDC_STATIC_REM                  1209
#define IDC_SLIDER1                     1210
#define IDC_SLIDER2                     1211
#define IDC_BUTTON3                     1212
#define IDC_BUTTON_MAN                  1212
#define IDC_COMBO_CT                    1213
#define IDC_COMBO_MT                    1214
#define IDC_BUTTON_DELETE               1215
#define IDC_BUTTON_DOWNLOAD             1216
#define IDC_BUTTON_ADD                  1217
#define IDC_BUTTON_EDIT                 1218
#define IDC_BUTTON_MFGEN                1219
#define IDC_STATIC_LAT                  1220
#define IDC_STATIC_LON                  1221
#define IDC_STATIC_NORTH                1222
#define IDC_STATIC_EAST                 1223
#define IDC_BUTTON_STOP                 1224

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1225
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
